### ISSUE TITLE
Superagent use throws error

### ISSUE THREAD

**Issue by jpodwys** [rhalff/x-ray-http-cache#1]
Hi, awesome module here!

Wanted to point out that the module [does not currently work](https://tonicdev.com/npm/x-ray-http-cache) because you're running `require('superagent')` but don't have superagent in your package.json. I would just submit a PR to fix the issue, but there are a few different options and I don't know which you prefer.
1. Add superagent to your package.json
2. Remove superagent from index.js and allow superagent-cache to [create a superagent instance](https://github.com/jpodwys/superagent-cache#basic-usage)
3. Allow the user to pass in their own superagent instance and pass it to superagent-cache
4. Combine `2` and `3` so it defaults to creating its own if the user doesn't provide one

**Comment by rhalff** [comment]
Thanks for reporting this, I wasn't aware.

I followed your suggestions and removed the require of superagent.

I went for option 4, you can pass your own superagent as an option and otherwise it will just use the instance superagent cache creates automatically.

I've released a new version which installs correctly now.
